# HW4
### Total points: 100 (5% of final grade).
### Due: 11:59 pm, Nov 7th, 2024
## Name: Joseph Dickerson

## Question 1. String Manipulation. (6 pts)
Extract the last names from the person list below, and save the result in a list. 

In [1]:
personList = [ 'Julia Smith', 'Francis Drake', 'Michael Mason',  
                'Jennifer Johnson', 'John Williams', 'Susanne Walker',  
                'Kermit the Frog', 'Dr. Melissa Franklin', 'Papa John', 
                'Walter John Miller', 'Frank Michael Robertson', 'Richard Robertson', 
                'Erik D. White', 'Vincent van Gogh', 'Dr. Dr. Matthew Malone', 
                'Rebecca Clark' ] 


last_names = [name.split()[-1] for name in personList]

print(last_names)


['Smith', 'Drake', 'Mason', 'Johnson', 'Williams', 'Walker', 'Frog', 'Franklin', 'John', 'Miller', 'Robertson', 'Robertson', 'White', 'Gogh', 'Malone', 'Clark']


## Question 2. String Manipulation. (6 pts)
Extract the first names from the person list below, and save the result in a list. 


In [2]:
personList = [ 'Julia Smith', 'Francis Drake', 'Michael Mason',  
                'Jennifer Johnson', 'John Williams', 'Susanne Walker',  
                'Kermit the Frog', 'Dr. Melissa Franklin', 'Papa John', 
                'Walter John Miller', 'Frank Michael Robertson', 'Richard Robertson', 
                'Erik D. White', 'Vincent van Gogh', 'Dr. Dr. Matthew Malone', 
                'Rebecca Clark' ] 

exclusions = ["Dr.", "Mr.", "Mrs.", "Ms."]

first_names = []

for name in personList:
    p1 = name.split()
    first_name = p1[0]
    index = 0

    while index < len(p1) and p1[index] in exclusions:
        index += 1

    if index < len(p1):
        first_names.append(p1[index])
    else:
        first_names.append("")

print(first_names)


['Julia', 'Francis', 'Michael', 'Jennifer', 'John', 'Susanne', 'Kermit', 'Melissa', 'Papa', 'Walter', 'Frank', 'Richard', 'Erik', 'Vincent', 'Matthew', 'Rebecca']


## Question 3. File read. (6 pts)
The targetted file is located here: https://caleb-huo.github.io/teaching/data/Python/Student_data.csv.
Read in this file and skip the header line ('Name', 'Hobby', 'Year_in_colledge', 'Initial_GPA', 'Study_time').
Prepare the data in the format of a list, with each element of the list being a tuple.
The first element of the list should be ('Dan', 'Football', 'freshman', '3.1', '10'). Print out the result.

In [3]:
import pandas as pd

data = pd.read_csv("https://caleb-huo.github.io/teaching/data/Python/Student_data.csv", header = None, skiprows = 1)
data.head

student_list = sorted(list(data.itertuples(index=False, name = None)))

print(student_list)


[('Amy', 'Swimming', 'senior', 3.0, 15), ('Ashely', 'Skiing', 'senior', 3.1, 15), ('Beth', 'Music', 'sophomore', 3.2, 20), ('Carl', 'Basketball', 'senior', 3.6, 14), ('Chris', 'Singing', 'freshman', 3.6, 19), ('Dan', 'Football', 'freshman', 3.1, 10), ('Dave', 'Fishing', 'junior', 3.9, 11), ('Emily', 'Running', 'junior', 3.3, 18), ('Frank', 'Cooking', 'sophomore', 3.4, 16), ('Lucas', 'Hiking', 'sophomore', 3.7, 13)]


## Question 4. List comprehension (6 pts)
Use the knowledge of list comprehension to create a dictionary based on the student list above.
The dictionary key should be students' name, and the value should be GPA in float type. Only output the elements of the dictionary with GPA >= 3.5. 

In [4]:
dictionary = {x[0]: x[3] for x in student_list if x[3] >= 3.5}

dictionary


{'Carl': 3.6, 'Chris': 3.6, 'Dave': 3.9, 'Lucas': 3.7}

## Question 5. Class basic. (6 pts)
Based on this student data, create a class Student.
The Student class should have the following 5 attributes:

- Name
- Hobby
- Year_in_colledge
- init_GPA
- study_time

And implement a "introduction()" method for this Student class.
This method should print out the following sentence:

- "Hello, this is XX. I am a XX. My hobby is XX!"

Then please create an object with the information of the first student (i.e., Dan). 
**Then use this introduction method**, we should expect to see the following

- Hello, this is Dan. I am a freshman. My hobby is Football!

Note that you may need to implement more methods for this class for future questions.

In [5]:
## implement your class here. 
## Note that you may need to implement more methods for this class for future questions.

import math

class Student:
    def __init__(self, name, hobby, year, gpa, time):
        self.name = name
        self.hobby = hobby
        self.year = year
        self.gpa = gpa
        self.time = time

    def introduction(self):
        print(f"Hello, this is {self.name}. I am a {self.year}. My hobby is {self.hobby}!")

    def getGPA(self):
        return round(self.gpa, 2)

    def getName(self):
        return(self.name)

    def updateGPA(self):
        if round((self.gpa + math.log(self.time, 10) - 1), 2) > 4.0:
            return 4.0
        else:
            return round((self.gpa + math.log(self.time, 10) - 1), 2)

    

In [6]:
## Please create an object with the information of the first student. 
## When using the introduction method.
## You should expect to see:
## Hello, this is Dan. I am a freshman. My hobby is Football!

dan = Student(name = student_list[5][0],
              hobby = student_list[5][1],
              year = student_list[5][2],
              gpa = student_list[5][3],
              time = student_list[5][4])

dan.introduction()


Hello, this is Dan. I am a freshman. My hobby is Football!


## Question 6. Get GPA (6 pts)
Implement a "getGPA()" method in the Student class in Question 5. 
You can directly append code to Student class in Question 5 instead of creating a new class.
In the "getGPA()" method, 
round the result such that there is only 2 digits after the decimal.
Then constructing a Student object with information of Lucas, and get the GPA for Lucas. 


In [7]:
lucas = Student(name = student_list[9][0],
                hobby = student_list[9][1],
                year = student_list[9][2],
                gpa = student_list[9][3],
                time = student_list[9][4])

lucas.getGPA()


3.7

## Question 7. Update GPA method. (6 pts) 
Implement a "updateGPA()" method in the Student class in Question 5. 
You can directly append code to Student class in Question 5 instead of creating a new class.
Studying and working hard will be helpful to improve GPA.
In the "updateGPA()" method, the new GPA = old GPA + log10(study_time) - 1.
Note that the new GPA should not be above 4.0.
If it is above, just set it to be 4.0.
Print out Emily's original GPA.
Also print out Emily's GPA aftering studing.


In [8]:
emily = Student(name = student_list[7][0],
                hobby = student_list[7][1],
                year = student_list[7][2],
                gpa = student_list[7][3],
                time = student_list[7][4])

emily.updateGPA()


3.56

## Question 8. Implement a StudyGroup Class. (6 pts)
This StudyGroup Class should have the following attribute:

- students: a list of Student objects

and the following methods:

- add(): add a Student to the StudyGroup class
- get_roster(): print out a list of all student names.

Then create the StudyGroup object, add all 10 students to the StudyGroup object, and finally, print out all students' names as a list.
Note that you may need to implement more methods for this class for future questions.


##

In [9]:
## implement your class here. 
## Note that you may need to implement more methods for this class for future questions.

import statistics

class StudyGroup():
    def __init__(self):
        self.students = []
        self.gpas = []

    def add(self, student):
        self.students.append(student)

    def addGPA(self, gpa):
        self.gpas.append(gpa)

    def get_roster(self):
        return ([name.getName() for name in self.students])

    def introduction_all(self):
        for name in self.students:
            name.introduction()

    def get_ave_GPA(self):
        return round(statistics.mean([gpa.getGPA() for gpa in self.gpas]), 2)

    def group_study(self):
        for student in self.students:
            updated_gpa = student.updateGPA()
            self.addGPA(updated_gpa)

    def get_high_GPA(self):
        gpa_dict = {student.getName(): student.updateGPA() for student in self.students}
        return gpa_dict



In [10]:
## Please create an object for the Study Group class.
## Then you may want to add all 10 students to this study group.
## Finally, print all students' name using the get_roster() method.

study_group = StudyGroup()
for i in range(0,10):
    group = Student(name = student_list[i][0],
                hobby = student_list[i][1],
                year = student_list[i][2],
                gpa = student_list[i][3],
                time = student_list[i][4])
    study_group.add(group)

roster = study_group.get_roster()

print(roster)


['Amy', 'Ashely', 'Beth', 'Carl', 'Chris', 'Dan', 'Dave', 'Emily', 'Frank', 'Lucas']


## Question 9. Introduce all students (6 pts)
Implement a introduction_all() method in the StudyGroup class in Question 8. 
You can directly append code to the StudyGroup class in Question 8 instead of creating a new class.
The introduction_all() method should print out the introduction of each student line by line.
The order of the introduction should be the alphabetic order.
For example, the first introduction should come from student Amy.
Show the result below.


In [11]:
study_group.introduction_all()


Hello, this is Amy. I am a senior. My hobby is Swimming!
Hello, this is Ashely. I am a senior. My hobby is Skiing!
Hello, this is Beth. I am a sophomore. My hobby is Music!
Hello, this is Carl. I am a senior. My hobby is Basketball!
Hello, this is Chris. I am a freshman. My hobby is Singing!
Hello, this is Dan. I am a freshman. My hobby is Football!
Hello, this is Dave. I am a junior. My hobby is Fishing!
Hello, this is Emily. I am a junior. My hobby is Running!
Hello, this is Frank. I am a sophomore. My hobby is Cooking!
Hello, this is Lucas. I am a sophomore. My hobby is Hiking!


## Question 10. Get average GPA. (6 pts)
Implement a "get_ave_GPA()" method in the StudyGroup class in Question 8. 
This method will return the average GPA of all students in this class.
**Round the result with 2 digits after the decimal.**
You can directly append code to the StudyGroup class in Question 8 instead of creating a new class.
Then print out the average GPA of all students in this study group.



In [12]:
gpas = StudyGroup()

for i in range (0,10):
    group = Student(name = student_list[i][0],
                hobby = student_list[i][1],
                year = student_list[i][2],
                gpa = student_list[i][3],
                time = student_list[i][4])
    gpas.addGPA(group)

gpas.get_ave_GPA()

3.39

## Question 11. Group Study. (6 pts) 
Implement a "group_study()" method in the StudyGroup class in Question 8. 
This method will let each student in the class study according to their study time.
You can directly append code to the StudyGroup class in Question 8 instead of creating a new class.
Then print out the average GPA after group study.



In [13]:
newGPAS = StudyGroup()

for i in range (0,10):
    group = Student(name = student_list[i][0],
                hobby = student_list[i][1],
                year = student_list[i][2],
                gpa = student_list[i][3],
                time = student_list[i][4])
    newGPAS.add(group)

newGPAS.group_study()

updateGPAS = [student.updateGPA() for student in newGPAS.students]

statistics.mean(updateGPAS)


3.56

## Question 12. Get highest GPA. (6 pts) 
Implement a "get_high_GPA()" method in the StudyGroup class in Question 8. 
This method will return the GPA and the student's name in the format of dictionary (i.e.,g {name:GPA}).
You can directly append code to the StudyGroup class in Question 8 instead of creating a new class.
Then print out the resulting dictionary (also after group study).



In [14]:
gpa_dict = newGPAS.get_high_GPA()
print(gpa_dict)


{'Amy': 3.18, 'Ashely': 3.28, 'Beth': 3.5, 'Carl': 3.75, 'Chris': 3.88, 'Dan': 3.1, 'Dave': 3.94, 'Emily': 3.56, 'Frank': 3.6, 'Lucas': 3.81}


## Question 13. Numpy operations. (6 pts)
We have created the following two numpy arrays A and B.
Perform element-wise calculation: |(A-B)/(A+B)|, where || indicates the absolute value.


In [15]:

import numpy as np

A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

array1 = np.abs((A - B) / (A + B))

print(array1)


[[0.14285714 0.14285714 0.63636364 0.42857143]
 [0.09090909 0.         0.33333333 0.09090909]]


## Question 14. Matrix operations. (6 pts)
Calculate $C = A \times B^\top$.
Print out $C$. 
What is the largest eigenvalues of matrix $C$


In [16]:
C = A @ B.T

print(C)

eigens = np.sort(np.linalg.eigvals(C))[::-1]

print(f"The largest eigenvalue of C is {eigens[0]}")

[[52 51]
 [58 71]]
The largest eigenvalue of C is 116.71095905705678


## Question 15. Matrix margin calculation. (6 pts)
Calculate row_sums and column_means for $A$.
Calculate row_standard deviation and column_variance for $B$.


In [17]:
print(f"Row sums for A: {np.sum(A, axis = 1)}")

print(f"Column means for A: {np.mean(A, axis = 0)}")

print(f"Row standard deviation for B: {np.std(B, axis = 1)}")

print(f"Column variance for B: {np.var(B, axis = 0)}")

Row sums for A: [18 15]
Column means for A: [4.  3.5 5.5 3.5]
Row standard deviation for B: [1.11803399 2.12132034]
Column variance for B: [1.   0.   0.25 0.25]


## Question 16. Stacking. (6 pts)
1. Generate a 1D numpy array containing 10 equally spaced values between 5 and 50.
2. Generate a 2D numpy array 2 rows by 10 columns with each element being 1.
3. Generate a 2D numpy array 3 rows by 5 columns with each element being 2.
4. Generate a 2D numpy array 3 rows by 5 columns with each element being -2.
5. Combine the arrays in step 3 and 4 to get a 2D numpy array with 3 rows and 10 columns.
6. Combine the arrays in step 1, 2 and 5 to get a 2D numpy array with 6 rows and 10 columns.
Print out this array (6 rows and 10 columns).


In [18]:
arr1 = np.arange(5, 51, 5)
print(f"1.\n {arr1}")

arr2 = np.full(20, 1).reshape(2, 10)
print(f"2.\n {arr2}")

arr3 = np.full(15, 2).reshape(3, 5)
print(f"3.\n {arr3}")

arr4 = np.full(15, -2).reshape(3, 5)
print(f"4.\n {arr4}")

arr5 = np.hstack((arr3, arr4))
print(f"5.\n {arr5}")

arr6 = np.vstack((arr1, arr2, arr5))
print(f"6.\n {arr6}")


1.
 [ 5 10 15 20 25 30 35 40 45 50]
2.
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
3.
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
4.
 [[-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
5.
 [[ 2  2  2  2  2 -2 -2 -2 -2 -2]
 [ 2  2  2  2  2 -2 -2 -2 -2 -2]
 [ 2  2  2  2  2 -2 -2 -2 -2 -2]]
6.
 [[ 5 10 15 20 25 30 35 40 45 50]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2 -2 -2 -2 -2 -2]
 [ 2  2  2  2  2 -2 -2 -2 -2 -2]
 [ 2  2  2  2  2 -2 -2 -2 -2 -2]]


## Note (4 pts):



### Homework should be uploaded to courseweb:
1. Save your compiled result as html file. Rename the file name as: hw4_Lastname_Firstname.html. To save .ipynb as .html, click file -> save and export Notebook as -> html.
2. Don't forget to write your name on the top of the html file.
3. ipynb file is not required. You only need to upload the html file to the [e-leaning](https://elearning.ufl.edu) website.

### If you generate a figure, please write appropriate figure title, labels, legend if necessary.

### If your code is not intuitive, please write comments to make the code readible. 


