# HW5
### Total points: 100 (5% of final grade).
### Due: 11:59 pm, Nov 21st, 2024
## Name: Joseph Dickerson

In [1]:
## you may need to use these two packages
import numpy as np
import pandas as pd


## Question 1. Numpy create. (5 pts)
Create a numpy array with 4 rows and 3 columns and with all elements being 1.
Replace the values in a sub-array, defined by the last two columns and last two rows, with 10.
Print out this array matrix.


In [2]:
array = np.ones((4,3))
array[2:, 1:] = 10

print(array)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1. 10. 10.]
 [ 1. 10. 10.]]


## Question 2. Numpy split and combine. (5 pts)
Split the following array (in the code section) vertically into three sub-arrays, 
and then horizentally combine these sub-arrays.
You should expect to see the following results.

array([[ 0,  1,  2,  3,  8,  9, 10, 11, 16, 17, 18, 19],  
&nbsp; &nbsp; &nbsp; &nbsp; [ 4,  5,  6,  7, 12, 13, 14, 15, 20, 21, 22, 23]])

In [3]:
data = np.arange(24).reshape(6,4)

split_array = np.vsplit(data, 3)

np.hstack(split_array)

array([[ 0,  1,  2,  3,  8,  9, 10, 11, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 12, 13, 14, 15, 20, 21, 22, 23]])

## Question 3. Frequency count. (5 pts)
$\pi$ with 100 digits after decimal is given below. There are a total of 101 digits. Which digit has the highest frequency? Purely use  code to extract this digit.


In [4]:
PI = "3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679"

def frequency(x):
    x = x.replace(".", "")
    digits = np.array(list(x), dtype=int)
    unique_digits, counts = np.unique(digits, return_counts=True)
    highest_frequency = unique_digits[np.argmax(counts)]

    return highest_frequency

print(frequency(PI))

9


## Question 4. Broadcasting. (5 pts)
A data matrix (3 rows and 5 columns) is given as the following.
Calculate the row median (median value for each row). 
Then multiply this row median with the data matrix (each column of the data matrix).

In [5]:
data2d = np.arange(15,0,-1).reshape(3,5)

medians = np.median(data2d, axis=1)

medians = medians.reshape(3,1)

print(medians * data2d)

[[195. 182. 169. 156. 143.]
 [ 80.  72.  64.  56.  48.]
 [ 15.  12.   9.   6.   3.]]


## Question 5. Broadcasting and matrix multiplication. (5 pts)
A data matrix (3 rows and 5 columns) is given as the following.
Calculate the column median (median value for each column). 
Then do matrix multiplication of the data matrix (3 by 5) with this column mean (5 by 1).

In [6]:
data2d = np.arange(15,0,-1).reshape(3,5)

medians2 = np.median(data2d, axis=0)

medians2 = medians2.reshape(5,1)


print(data2d @ medians2)

[[530.]
 [330.]
 [130.]]


## Question 6. Create a Series. (5 pts)
Using list comprehension to create the following Series:

101 &nbsp; &nbsp; &nbsp; &nbsp; 15.0  
102 &nbsp; &nbsp; &nbsp; &nbsp; 25.0  
103 &nbsp; &nbsp; &nbsp; &nbsp; 35.0  
104 &nbsp; &nbsp; &nbsp; &nbsp; 45.0  
105 &nbsp; &nbsp; &nbsp; &nbsp; 55.0  
106 &nbsp; &nbsp; &nbsp; &nbsp; 65.0  
107 &nbsp; &nbsp; &nbsp; &nbsp; 75.0  
108 &nbsp; &nbsp; &nbsp; &nbsp; 85.0  
109 &nbsp; &nbsp; &nbsp; &nbsp; 95.0  
dtype: float64  


In [7]:
data = [x * 10.0 + 5 for x in range(1, 10)]

series = pd.Series(data, index=range(101,110))

print(series)

101    15.0
102    25.0
103    35.0
104    45.0
105    55.0
106    65.0
107    75.0
108    85.0
109    95.0
dtype: float64


## Question 7. Create DataFrame. (5 pts)
Create the following DataFrame object and assign it to a variable. 
Convert the first column (company) to index. 
Print out this variable.


         company   price   ticker
    0     Amazon  2375.0     AMZN
    1  Microsoft   178.6     MSFT
    2      Apple   179.2     AAPL


In [8]:
data = {
    'company': ['Amazon', 'Microsoft', 'Apple'],
    'price': [2375.0, 178.6, 179.2],
    'ticker': ['AMZN', 'MSFT', 'AAPL']
}

dataframe = pd.DataFrame(data)

dataframe.set_index("company")

print(dataframe)


     company   price ticker
0     Amazon  2375.0   AMZN
1  Microsoft   178.6   MSFT
2      Apple   179.2   AAPL


## Question 8. File read. (5 pts)
The stock price data is located here: https://caleb-huo.github.io/teaching/data/Python/stock_price.csv.
Read in this file to create a dataFrame using Pandas and set the Date colunms as the index (should make it as datetimeindex).
Print out the last 10 lines of this dataFrame

In [9]:
file = pd.read_csv("https://caleb-huo.github.io/teaching/data/Python/stock_price.csv")

df = pd.DataFrame(file)

print(df[-10:])

           Date        TSLA        AAPL       GOOG        META
990  2022-11-01  227.820007  150.400497  90.500000   95.199997
991  2022-11-02  214.979996  144.789810  87.070000   90.540001
992  2022-11-03  215.309998  138.650009  83.489998   88.910004
993  2022-11-04  207.470001  138.380005  86.699997   90.790001
994  2022-11-07  197.080002  138.919998  88.650002   96.720001
995  2022-11-08  191.300003  139.500000  88.910004   96.470001
996  2022-11-09  177.589996  134.869995  87.400002  101.470001
997  2022-11-10  190.720001  146.869995  94.169998  111.870003
998  2022-11-11  195.970001  149.699997  96.730003  113.019997
999  2022-11-14  193.427994  148.830002  95.690002  115.440002


## Question 9. Apply functions for dataFrame. (5 pts)
For the stock price data in January 2022, what is the coefficient of variation $CV = \frac{\sigma}{\mu}$ for each stock? where $\sigma$ indicates standard deviation, and $\mu$ indicates mean.

In [10]:
date_range = (df["Date"] >= "2022-01-01") & (df["Date"] <= "2022-01-31")

jan_data = df.loc[date_range].set_index("Date")

coef_vars = (jan_data.std() / jan_data.mean())

print(coef_vars)

TSLA    0.094070
AAPL    0.039801
GOOG    0.037609
META    0.045650
dtype: float64


## Question 10. Apply functions for dataFrame. (5 pts)
First, calculate daily stock return, which is defined as $\frac{price_{day1} - price_{day0}}{price_{day0}}$. Here, day1 is the currentm trading day and day0 is the previous trading day. For each stock, what is the frequency of the following events:
1. daily stock return >= 0.05
2. daily stock return >= 0.10
3. daily stock return >= 0.15

Prepare the result as a dataFrame. In this question, you need to consider the data in all available time. You may want to use the pct_change method (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pct_change.html). 

In [11]:
df1 = df.set_index("Date").pct_change()

def thresh_count(df, thresholds=[0.05, 0.10, 0.15]):
    count = pd.DataFrame(index=df.columns, columns=thresholds)

    for threshold in thresholds:    
        count[threshold] = (df >= threshold).sum()
    
    return count

thresh_count(df1)

0.05  0.10  0.15
TSLA    93    22     5
AAPL    17     3     0
GOOG    17     1     0
META    36     4     1

## Question 11. Daily return frequency summary. (5 pts)
For stock TSLA, count the frequency of the daily stock return of the following categories:  
(-inf, -0.1]  
(-0.1, -0.05]  
(-0.05, -0.01]  
(-0.01, 0.01]  
(0.01, 0.05]  
(0.05, 0.1]  
(0.1, inf]  

In this question, you need to consider the data in all available time.

In [12]:
def freq_count(df, column):
    bins = [-float("inf"), -0.1, -0.05, -0.01, 0.01, 0.05, 0.1, float("inf")]
    categories = pd.cut(df[column], bins=bins)
    counts = categories.value_counts().sort_index()
    return counts

freq_count(df1, "TSLA")

TSLA
(-inf, -0.1]       14
(-0.1, -0.05]      65
(-0.05, -0.01]    235
(-0.01, 0.01]     292
(0.01, 0.05]      300
(0.05, 0.1]        71
(0.1, inf]         22
Name: count, dtype: int64

## Question 12. Groupby. (5 pts)
In year 2021, what is the mean stock return for each stock in each month?
Prepare the result as a dataFrame, in which month is the index, and stock symbol is the column names.

In [13]:
df1.index = pd.to_datetime(df1.index)

df2 = df1.loc["2021-01-01":"2021-12-31"]

def mean_return(df):
    mean_returns = df.groupby(df.index.month).mean()
    return mean_returns

df_groups = mean_return(df2)

df_groups

TSLA      AAPL      GOOG      META
Date                                        
1     0.006952 -0.000013  0.002684 -0.002667
2    -0.007729 -0.004269  0.005698 -0.000036
3     0.001026  0.000574  0.000812  0.006093
4     0.003404  0.003591  0.007412  0.004911
5    -0.005912 -0.002470  0.000138  0.000701
6     0.004091  0.004349  0.001776  0.002657
7     0.000728  0.003096  0.003701  0.001323
8     0.003323  0.001957  0.003348  0.002920
9     0.002631 -0.003267 -0.004085 -0.005173
10    0.017770  0.002785  0.005229 -0.002032
11    0.002249  0.004870 -0.001799  0.000298
12   -0.002938  0.003422  0.000778  0.001832

## Question 13. Wide format to long format. (5 pts)
Convert the dataFrame in the previous question into long format.
The results should have three columns: month, stock symbol, and the mean stock return.
Print the first 10 lines of the results.

In [14]:
df_long = df_groups.reset_index().melt(id_vars="Date", value_vars=["TSLA", "AAPL", "GOOG", "META"])

print(df_long[0:10])

   Date variable     value
0     1     TSLA  0.006952
1     2     TSLA -0.007729
2     3     TSLA  0.001026
3     4     TSLA  0.003404
4     5     TSLA -0.005912
5     6     TSLA  0.004091
6     7     TSLA  0.000728
7     8     TSLA  0.003323
8     9     TSLA  0.002631
9    10     TSLA  0.017770


## Question 14. Long format to wide format. (5 pts)
Convert the dataFrame in the previous question into wide format.
The results should have (1) 12 columns indicating 12 months; 
(2) 4 stock symbols as index.
Each cell in the dataFrame indicates the return of a stock at a certain month.


In [15]:
df_wide = df_long.pivot(index="variable", columns="Date")

print(df_wide)

             value                                                    \
Date            1         2         3         4         5         6    
variable                                                               
AAPL     -0.000013 -0.004269  0.000574  0.003591 -0.002470  0.004349   
GOOG      0.002684  0.005698  0.000812  0.007412  0.000138  0.001776   
META     -0.002667 -0.000036  0.006093  0.004911  0.000701  0.002657   
TSLA      0.006952 -0.007729  0.001026  0.003404 -0.005912  0.004091   

                                                                      
Date            7         8         9         10        11        12  
variable                                                              
AAPL      0.003096  0.001957 -0.003267  0.002785  0.004870  0.003422  
GOOG      0.003701  0.003348 -0.004085  0.005229 -0.001799  0.000778  
META      0.001323  0.002920 -0.005173 -0.002032  0.000298  0.001832  
TSLA      0.000728  0.003323  0.002631  0.017770  0.002249 -0.002938 

## Question 15. Max and Min. (5 pts)
Based on the dataFrame (mean stock return for each month) in **Question 12**,
for each stock,
calculate 4 attributes including: 
(1) the max "mean stock return", 
(2) the month of the max "mean stock return",
(3) the min "mean stock return", 
and (4) the month of the min "mean stock return".
Prepare the results as a dataFrame (stocks on rows and the 4 attributes on columns).
Make sure the month is rendered as integer.


In [16]:
def attributes(df):
    # new dataframe
    new_df = pd.DataFrame(index=df.columns, columns=["max_return", "max_month", "min_return", "min_month"])
    
    for x in df.columns:
        stock_data = df[x]
    
        max_return = stock_data.max()
        max_month = stock_data.idxmax()  
        min_return = stock_data.min()
        min_month = stock_data.idxmin()  
        
        new_df.loc[x] = [max_return, max_month, min_return, min_month]
    
    return new_df

attributes(df_groups)

max_return max_month min_return min_month
TSLA    0.01777        10  -0.007729         2
AAPL    0.00487        11  -0.004269         2
GOOG   0.007412         4  -0.004085         9
META   0.006093         3  -0.005173         9

## Question 16. Multi-level Groupby. (5 pts)
Using all data in years 2020 and 2021, calcualte the sharpe ratio for each stock within each month within each year. 
The sharpe ratio is defined as (mean stock return)/(standard deviation of the stock return).
For the resulting dataFrame, year and month should be the multi-level index, and the columns are the 4 stocks.

In [17]:
## Sadly I am unable to finish 16-18 in time before my shift begins. A time managment fault on my part.

# def sharpe(df):
    # (df.groupby(df.index.month).mean())/df.groupby(df.index.month).stdev()

# df_sharpe_means = mean_return(df_sharpe)

# df_sharpe_means



# Question 17. Merge (5 pts).
Based on the result from the previous question, create (A) dataFrame of Sharpe ratio in 2020 and (B) dataFrame of Sharpe ratio in 2021.
Then merge (A) dataFrame of Sharpe ratio in 2020 and (B) dataFrame of Sharpe ratio in 2020. 
The merged keys should be month. Also add suffixes ("_2020" and "_2021") to distinguish years.


In [18]:
## Sadly I am unable to finish 16-18 in time before my shift begins. A time managment fault on my part.


## Question 18. Combination of skill sets (5 pts).
For each of the three year from 2019/1/1 to 2021/12/31, 
calculate the days differece (in absolute value) between the date with the most positive stock return and the date with the most negative stock return.

In [19]:
## Sadly I am unable to finish 16-18 in time before my shift begins. A time managment fault on my part.


## Question 19. Data cleaning (5pts). 
The following dataframe is given. Perform data cleaning, including the following sequencial steps:
  - replace -99 to NA
  - remove missing value (rows with any missing values)
  - remove duplicates
  - convert to integer
  - use the map function to calculate the sum of all digits for each element of the Series, for each column
  - sort by l1 (decending order)






In [20]:
## This data is given

data = pd.DataFrame({"l1": [1,2,3,18,13, 1, 15,6,-99,21,3,np.nan], 
"l2": [1,np.nan,3,7,np.nan,1, 5,-99,-99,3,3,9]})
data.head()


l1   l2
0   1.0  1.0
1   2.0  NaN
2   3.0  3.0
3  18.0  7.0
4  13.0  NaN

In [21]:
data.replace(-99, np.nan, inplace=True)
data.dropna(inplace=True)
data.drop_duplicates(inplace=True)
data.astype(int)

print(f"Sum of l1: {data.l1.map(int).sum()}")
print(f"Sum of l2: {data.l2.map(int).sum()}")

data.sort_values(by="l1", ascending=False, inplace=True)

print(data)

Sum of l1: 58
Sum of l2: 19
     l1   l2
9  21.0  3.0
3  18.0  7.0
6  15.0  5.0
2   3.0  3.0
0   1.0  1.0


## Note (5 pts):



### Homework should be uploaded to courseweb:
1. Save your compiled result as html file. Rename the file name as: hw5_Lastname_Firstname.html. To save .ipynb as .html, click file -> save and export Notebook as -> html.
2. Don't forget to write your name on the top of the html file.
3. ipynb file is not required. You only need to upload the html file to the [e-leaning](https://elearning.ufl.edu) website.

### If you generate a figure, please write appropriate figure title, labels, legend if necessary.

### If your code is not intuitive, please write comments to make the code readible. 


